"""AAdded attributes

Revision ID: 8542b63dfdd7
Revises: 475eda9c5afb
Create Date: 2024-11-06 00:08:45.903243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8542b63dfdd7'
down_revision: Union[str, None] = '475eda9c5afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('attributes', sa.JSON(), nullable=True))
    op.drop_column('order_items', 'color')
    op.drop_column('order_items', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'attributes')
    # ### end Alembic commands ###
